package fxTreenipk.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import fxTreenipk.*;
// Generated by ComTest END
import luokat.Treeni;

/**
 * Test class made by ComTest
 * @version 2022.11.11 13:08:46 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TreeniTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi72 */
  @Test
  public void testRekisteroi72() {    // Treeni: 72
    Treeni treeni1 = new Treeni(); 
    assertEquals("From: Treeni line: 74", 0, treeni1.getID()); 
    treeni1.rekisteroi(); 
    Treeni treeni2 = new Treeni(); 
    treeni2.rekisteroi(); 
    int n1 = treeni1.getID(); 
    int n2 = treeni2.getID(); 
    assertEquals("From: Treeni line: 80", n2-1, n1); 
  } // Generated by ComTest END
}