package fxTreenipk.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import fxTreenipk.*;
// Generated by ComTest END
import luokat.Liike;
import luokat.Treeni;
import luokat.Treenipk;
import luokat.Viikko;

/**
 * Test class made by ComTest
 * @version 2022.11.12 17:04:47 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TreenipkTest {



  // Generated by ComTest BEGIN
  /** testAnnaTreenit69 
 * @throws SailoException jos ei mahu*/
  @Test
  public void testAnnaTreenit69() throws SailoException {    // Treenipk: 69
    Treenipk treenipk = new Treenipk(); 
    Viikko vko1 = new Viikko(), vko2 = new Viikko(), vko3 = new Viikko(); 
    vko1.rekisteroi(); vko2.rekisteroi(); vko3.rekisteroi(); 
    int id1 = vko1.getID(); 
    int id2 = vko2.getID(); 
    Treeni treeni1 = new Treeni(id1); treenipk.lisaa(treeni1); 
    Treeni treeni2 = new Treeni(id1); treenipk.lisaa(treeni2); 
    Treeni treeni3 = new Treeni(id2); treenipk.lisaa(treeni3); 
    Treeni treeni4 = new Treeni(id2); treenipk.lisaa(treeni4); 
    Treeni treeni5 = new Treeni(id2); treenipk.lisaa(treeni5); 
    List<Treeni> loytyneet; 
    loytyneet = treenipk.annaTreenit(vko3); 
    assertEquals("From: Treenipk line: 85", 0, loytyneet.size()); 
    loytyneet = treenipk.annaTreenit(vko1); 
    assertEquals("From: Treenipk line: 87", 2, loytyneet.size()); 
    assertEquals("From: Treenipk line: 88", true, loytyneet.get(0) == treeni1); 
    assertEquals("From: Treenipk line: 89", true, loytyneet.get(1) == treeni2); 
    loytyneet = treenipk.annaTreenit(vko2); 
    assertEquals("From: Treenipk line: 91", 3, loytyneet.size()); 
    assertEquals("From: Treenipk line: 92", true, loytyneet.get(0) == treeni3); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaLiikkeet105 
 * @throws SailoException jos ei mahu*/
  @Test
  public void testAnnaLiikkeet105() throws SailoException {    // Treenipk: 105
    Treenipk treenipk = new Treenipk(); 
    Treeni treeni1 = new Treeni(), treeni2 = new Treeni(), treeni3 = new Treeni(); 
    treeni1.rekisteroi(); treeni2.rekisteroi(); treeni3.rekisteroi(); 
    int id1 = treeni1.getID(); 
    int id2 = treeni2.getID(); 
    Liike liike1 = new Liike(id1); treenipk.lisaa(liike1); 
    Liike liike2 = new Liike(id1); treenipk.lisaa(liike2); 
    Liike liike3 = new Liike(id2); treenipk.lisaa(liike3); 
    Liike liike4 = new Liike(id2); treenipk.lisaa(liike4); 
    Liike liike5 = new Liike(id2); treenipk.lisaa(liike5); 
    List<Liike> loytyneet; 
    loytyneet = treenipk.annaLiikkeet(treeni3); 
    assertEquals("From: Treenipk line: 121", 0, loytyneet.size()); 
    loytyneet = treenipk.annaLiikkeet(treeni1); 
    assertEquals("From: Treenipk line: 123", 2, loytyneet.size()); 
    assertEquals("From: Treenipk line: 124", true, loytyneet.get(0) == liike1); 
    assertEquals("From: Treenipk line: 125", true, loytyneet.get(1) == liike2); 
    loytyneet = treenipk.annaLiikkeet(treeni2); 
    assertEquals("From: Treenipk line: 127", 3, loytyneet.size()); 
    assertEquals("From: Treenipk line: 128", true, loytyneet.get(0) == liike3); 
  } // Generated by ComTest END
}