package fxTreenipk.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import fxTreenipk.*;
// Generated by ComTest END
import luokat.Viikko;

/**
 * Test class made by ComTest
 * @version 2022.10.29 14:23:50 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ViikkoTest {


  // Generated by ComTest BEGIN
  /** testRekisteroi39 */
  @Test
  public void testRekisteroi39() {    // Viikko: 39
    Viikko vko1 = new Viikko(); 
    Viikko vko2 = new Viikko(); 
    assertEquals("From: Viikko line: 42", 0, vko1.getID()); 
    vko1.rekisteroi(); 
    vko2.rekisteroi(); 
    int n1 = vko1.getID(); 
    int n2 = vko2.getID(); 
    assertEquals("From: Viikko line: 47", n2-1, n1); 
  } // Generated by ComTest END
}