package fxTreenipk.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import fxTreenipk.*;
// Generated by ComTest END
import luokat.Viikko;
import luokat.Viikot;

/**
 * Test class made by ComTest
 * @version 2022.10.29 15:42:36 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ViikotTest {


  // Generated by ComTest BEGIN
  /** 
   * testLisaa28 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa28() throws SailoException {    // Viikot: 28
    Viikot viikot = new Viikot(); 
    Viikko vko1 = new Viikko(), vko2 = new Viikko(); 
    assertEquals("From: Viikot line: 32", 0, viikot.getLkm()); 
    viikot.lisaa(vko1); assertEquals("From: Viikot line: 33", 1, viikot.getLkm()); 
    viikot.lisaa(vko2); assertEquals("From: Viikot line: 34", 2, viikot.getLkm()); 
    viikot.lisaa(vko1); assertEquals("From: Viikot line: 35", 3, viikot.getLkm()); 
    assertEquals("From: Viikot line: 36", vko1, viikot.anna(0)); 
    assertEquals("From: Viikot line: 37", vko2, viikot.anna(1)); 
    assertEquals("From: Viikot line: 38", vko1, viikot.anna(2)); 
    assertEquals("From: Viikot line: 39", false, viikot.anna(1) == vko1); 
    assertEquals("From: Viikot line: 40", true, viikot.anna(1) == vko2); 
    try {
    assertEquals("From: Viikot line: 41", vko1, viikot.anna(3)); 
    fail("Viikot: 41 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    viikot.lisaa(vko1); assertEquals("From: Viikot line: 42", 4, viikot.getLkm()); 
    viikot.lisaa(vko1); assertEquals("From: Viikot line: 43", 5, viikot.getLkm()); 
  } // Generated by ComTest END
}